mysql_old_root_password: mysql_root_password
mysql_root_password: mysql_root_password

mysql_db: "ecomdb"
mysql_user: "ecomuser"
mysql_password: "ecompassword"

http_host: "_"
http_conf: "my_ansible_site"
http_port: "80"